# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


development:
  STRIPE_PUBLISHABLE_KEY: pk_test_4WPD5PCYjV8zjMVqrkuF4Odf
  STRIPE_SECRET_KEY: sk_test_Z9qTRivw6k6m2sSJPyem10KU
test:
  STRIPE_PUBLISHABLE_KEY: pk_test_4WPD5PCYjV8zjMVqrkuF4Odf
  STRIPE_SECRET_KEY: sk_test_Z9qTRivw6k6m2sSJPyem10KU
production:
  STRIPE_PUBLISHABLE_KEY: pk_live_4hVk7gMtBwrW4aVS16wy25ho
  STRIPE_SECRET_KEY: sk_live_LDM0WTlohDmD0Dn4ZmFpzuGP