development:
  adapter: postgresql
  encoding: unicode
  database: pubhub_dev
  pool: 5
  username: danielschonfeld
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pubhub_test
  pool: 5
  username: danielschonfeld
  password:
